name: Code Quality

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm install -g sonarqube-scanner
    - run: npm run lint
    - run: |
        npm run test:coverage
        sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }}
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}